### ISSUE TITLE
Les "device_tracker" ne fonctionnent plus depuis la mise à jour du firmware de la Bbox (Fast5330b-r1) en version 23.7.8

### ISSUE THREAD

**Issue by mcpfr** [earion68/hass_custom_bbox#4]
Bonjour,

Je me permets de vous remonter ce problème.

Depuis la mise à jour en version 23.7.8 et son redémarrage, les informations des "device.tracker" ne sont plus fonctionnelles.

Premières constatations :

- Il n'y a pas d' erreur dans les logs HA.
- Les informations remontées par l'API semblent ne pas changées.

[{"hosts":{"list":[
    {"id":1,
    "hostname":"xxxxxxx",
    "macaddress":"xxxxxxxxxxxxxxx",
    "ipaddress":"xxxxxxxxxxxx",
   "active":1,

Par avance merci de votre aide

Cordialement
Mcp

**Comment by earion68** [comment]
C'est curieux, on dirait que je n'ai pas cette version du firmware en "opérationnel", whatever that means.
Ci-dessous les informations de ma BBox (tout juste redémarrée pour être sûr), je pourrais voir le vôtre ?

![image](https://github.com/earion68/hass_custom_bbox/assets/54678154/3922309e-8d46-49a1-aabe-41990a0f5569)

Inutile de préciser que dans ma situation actuelle, tout fonctionne bien. Il faudrait au moins que j'arrive à reproduire le problème pour tenter de le corriger.

**Comment by mcpfr** [comment]
Merci de votre retour,

La mienne est passée en 23.7.8
![image](https://github.com/earion68/hass_custom_bbox/assets/79054086/97ed7e8f-ccaa-43e7-b531-cfd4c07c7c07)

**Comment by earion68** [comment]
Merci, je vais essayer de forcer la mise à jour afin de reproduire (et corriger si possible) le problème.

**Comment by mcpfr** [comment]
Merci,

N'hésitez pas si vous avez besoin d'informations ou de tests

Mcp

**Comment by JimmyTournemaine** [comment]
Hello, est-ce que tu as pu avancer sur le sujet ?

J'ai regardé un peu pour essayer de comprendre. Voici l'exception levée:

```
2024-02-16 11:49:46.288 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform legacy custom_bbox
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 301, in async_setup_legacy
    scanner = await hass.async_add_executor_job(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/device_tracker.py", line 35, in get_scanner
    scanner = BboxDeviceScanner(config[DOMAIN])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/device_tracker.py", line 54, in __init__
    self.success_init = self._update_info()
                        ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/device_tracker.py", line 82, in _update_info
    result = box.get_all_connected_devices()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/pybbox.py", line 116, in get_all_connected_devices
    resp = api.execute_api_request()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/custom_bbox/bboxApiCall.py", line 62, in execute_api_request
    raise Exception('Error {} with request {}\n{}'.format(
Exception: Error 401 with request http://192.168.1.254/api/v1/hosts
{'exception': {'domain': 'v1/hosts', 'code': '401', 'errors': [{'name': '', 'reason': 'Operation requires authentication'}]}}
```

Il semblerait que désormais l'authentification soit obligatoire pour certains endpoint.
[cf la doc du endpoint](https://api.bbox.fr/doc/apirouter/#api-LAN-GetHosts)

> Authentication required on LAN
> Authentication is required to access to this API on local network. Cookie "BBOX_ID" MUST be set with the value retrieved from login API

Dans le code d'appel au WS, on a `self.auth.is_authentified()` qui est `False` et donc le cookie d'authentification n'est pas passé d'où le 401.

**Comment by earion68** [comment]
J'ai enfin reçu la mise à jour.

J'ai commit un quick fix dans la branche **quickfix_login** et le commit https://github.com/earion68/hass_custom_bbox/commit/c6a150e5959b0ef5f855ac43f5e09b131feee455 en particulier 
mot de passe de ta Bbox à mettre en dur pour le moment.
Aussi, la Bbox doit répondre à son addresse mabbox.bytel.fr.

Chez moi ça fonctionne à nouveau. Tu peux me dire si ça fait le job chez toi ? Si oui je regarderai pour instrumentaliser un peu via la config du composant.

![image](https://github.com/earion68/hass_custom_bbox/assets/54678154/0479eca8-b1fc-4f24-9c52-dbb263fa9241)

**Comment by earion68** [comment]
Parviens-tu à faire un ping vers cette addresse?


________________________________

**Comment by mcpfr** [comment]
oui, et l'adresse est bien résolu depuis le ssh sur H.A

**Comment by mcpfr** [comment]
Pour information, je ne suis pas sur le 168.xxx mais un 10.xx

**Comment by earion68** [comment]
j'ignore pourquoi il a fallu que je remplace la ligne 81 par la ligne 82.
Essaie peut-être de faire l'inverse de ton côté.

**Comment by mcpfr** [comment]
Bon....
Cela refonctionne, mais il a fallu que je modifie le fichier bboxApiURL.py
pour forcer directement le type LAN et en HTTPS (section ligne 52/61)

# Check if the ip is LAN or WAN
        
url = "https://{}".format(self.ip)
self.authentication_type = BboxConstant.AUTHENTICATION_TYPE_LOCAL
        
#if net.IPAddress(self.ip).is_private():
#    url = "http://{}".format(self.ip)
#    self.authentication_type = BboxConstant.AUTHENTICATION_TYPE_LOCAL
#else:
#    url = "https://{}:{}".format(self.ip,
#                                 BboxConstant.DEFAULT_REMOTE_PORT)
#    self.authentication_type = BboxConstant.AUTHENTICATION_TYPE_REMOTE

**Comment by earion68** [comment]
Merci pour la confirmation.

J'ai implémenté les changements dans la branche **main**, la différence maintenant c'est qu'il faut spécifier le mot de passe de la Bbox dans configuration.yaml, c'est plus propre.

c.f. https://github.com/earion68/hass_custom_bbox/blob/main/README.md

Je ferme le ticket. Merci pour ton aide !

**Comment by mcpfr** [comment]
Bonjour,

Je viens de mettre en place l'intégration et cela fonctionne, il a juste fallu que je précise le "host: mabbox.bytel.fr" (ip en: 10.x.x.,)

Un grand merci à vous et surtout n'hésitez pas a me contacter en cas de besoin pour des tests, même sur d'autres points

Merci 

Mcp
