### ISSUE TITLE
erreur password

### ISSUE THREAD

**Issue by dude29300** [earion68/hass_custom_bbox#7]
![image](https://github.com/earion68/hass_custom_bbox/assets/60757476/ac7320fa-ad2e-47f4-a41d-b0994c1bec31)
J'essai votre module mais je rencontre ces erreurs.
Quelles sont les paramètres à modifier ?
Pour info, ma bbox est en lan 192.168.0.0

**Comment by earion68** [comment]
Quelle version de Home Assistant ?
Êtes-vous sûr d'avoir la dernière version du code de custom_bbox ? En effet j'ai fait une mise à jour très récemment pour supporter le nouveau firmware Bbox.

**Comment by dude29300** [comment]
Bonsoir, voici la version de HA: 
![image](https://github.com/earion68/hass_custom_bbox/assets/60757476/c4ff89d5-e4f3-44aa-8cdc-23896e0df288)

j'ai télécharge votre version aujourd'hui pour l'essayer

**Comment by earion68** [comment]
Je ne parviens pas à reproduire le problème de mon côté. Mais dans tous les cas c'est un souci de validation du YAML en cliquant sur **Vérifier la configuration**. Cela de devrait pas empêcher Home Assistant de démarrer.

**Comment by dude29300** [comment]
j'ai refais mon fichier configuration.yaml et je n'ai plus d'erreur, surement un espace qui trainait.
désole du derangement
